/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Permission } from "./Permission";
import { PermissionCountArgs } from "./PermissionCountArgs";
import { PermissionFindManyArgs } from "./PermissionFindManyArgs";
import { PermissionFindUniqueArgs } from "./PermissionFindUniqueArgs";
import { CreatePermissionArgs } from "./CreatePermissionArgs";
import { UpdatePermissionArgs } from "./UpdatePermissionArgs";
import { DeletePermissionArgs } from "./DeletePermissionArgs";
import { PermissionService } from "../permission.service";
@graphql.Resolver(() => Permission)
export class PermissionResolverBase {
  constructor(protected readonly service: PermissionService) {}

  async _permissionsMeta(
    @graphql.Args() args: PermissionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Permission])
  async permissions(
    @graphql.Args() args: PermissionFindManyArgs
  ): Promise<Permission[]> {
    return this.service.permissions(args);
  }

  @graphql.Query(() => Permission, { nullable: true })
  async permission(
    @graphql.Args() args: PermissionFindUniqueArgs
  ): Promise<Permission | null> {
    const result = await this.service.permission(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Permission)
  async createPermission(
    @graphql.Args() args: CreatePermissionArgs
  ): Promise<Permission> {
    return await this.service.createPermission({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Permission)
  async updatePermission(
    @graphql.Args() args: UpdatePermissionArgs
  ): Promise<Permission | null> {
    try {
      return await this.service.updatePermission({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Permission)
  async deletePermission(
    @graphql.Args() args: DeletePermissionArgs
  ): Promise<Permission | null> {
    try {
      return await this.service.deletePermission(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
